name: food_sellers_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.2
  firebase_storage: ^11.1.1

  image_picker: ^0.8.7+4
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  shared_preferences: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Bebas
      fonts:
        - asset:  assets/fonts/BebasNeue-Regular.ttf
    - family: Lobster
      fonts:
        - asset:  assets/fonts/Lobster-Regular.ttf
    - family: Signatra
      fonts:
        - asset:  assets/fonts/Signatra.ttf
    - family: VarelaRound
      fonts:
        - asset:  assets/fonts/VarelaRound-Regular.ttf